version: '2.1'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/github.com/gildasch/gildas-ai
    working_dir: /go/src/github.com/gildasch/gildas-ai
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      'go test -v ./...'

  gildas-ai:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9850:8080
    network_mode: bridge
    restart: always

networks:
  default:
    external:
      name: bridge
